# Auto-labeling rules for PRs based on changed files
# https://github.com/actions/labeler

# Documentation changes
"area: documentation":
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**/*"

# Tests
"area: tests":
  - changed-files:
      - any-glob-to-any-file:
          - "tests/**/*"
          - "**/test_*.py"
          - "**/*_test.py"

# CI/CD and workflows
"area: ci":
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"
          - ".gitignore"
          - ".pre-commit-config.yaml"

# Dependencies
"type: dependencies":
  - changed-files:
      - any-glob-to-any-file:
          - "pyproject.toml"
          - "requirements*.txt"
          - "poetry.lock"
          - "Pipfile.lock"

# Core functionality
"area: core":
  - changed-files:
      - any-glob-to-any-file:
          - "src/basic_agent_chat_loop/components/**/*"
          - "src/basic_agent_chat_loop/chat_loop.py"
          - "src/basic_agent_chat_loop/main.py"

# Configuration
"area: config":
  - changed-files:
      - any-glob-to-any-file:
          - "src/basic_agent_chat_loop/chat_config.py"
          - "**/.chatrc"
          - "**/config*.py"

# Templates and examples
"area: templates":
  - changed-files:
      - any-glob-to-any-file:
          - "examples/**/*"
          - "templates/**/*"
